### ISSUE TITLE
NoSuchMethodError: internalCreateDataFrame

### ISSUE THREAD

**Issue by emmanuelmillionaer** [twosigma/flint#55]
Thank you for this amazing library! 🥇 
I'm running Spark 2.2.0 and tried to initialize a clock:

```
clock = clocks.uniform(sqlContext, frequency="1day")
```

This threw an exception:

```
py4j.protocol.Py4JJavaError: An error occurred while calling z:com.twosigma.flint.timeseries.Clocks.uniform.
: java.lang.NoSuchMethodError: org.apache.spark.sql.SparkSession.internalCreateDataFrame$default$3()Z
	at org.apache.spark.sql.DFConverter$.toDataFrame(DFConverter.scala:42)
	at com.twosigma.flint.timeseries.clock.Clock.asTimeSeriesRDD(Clock.scala:148)
	at com.twosigma.flint.timeseries.Clocks$.uniform(Clocks.scala:54)
	at com.twosigma.flint.timeseries.Clocks.uniform(Clocks.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

```

**NoSuchMethodError:  org.apache.spark.sql.SparkSession.internalCreateDataFrame$default$3()Z**

I found this method in the docs: https://spark.apache.org/docs/preview/api/java/org/apache/spark/sql/SparkSession.html#internalCreateDataFrame(org.apache.spark.rdd.RDD,%20org.apache.spark.sql.types.StructType)

However it seems like it's not available in the version I'm running? Can you please provide me with a hint on how to resolve this issue? Thanks! 👍

**Comment by icexelloss** [comment]
@emmanuelmillionaer Hi currently Flint only works with Spark 2.3+

**Comment by icexelloss** [comment]
@LeoDashTM I suspect clock table is not on the left side? Please create a another issue so we don't talk about two different issues here.
